google_analytics:
  data_from: '1'
  tid: 'UA-XXXXX-X'
  ga:
    view_id: 'XXXXX'
    client_id_dimension: 'ga:dimensionX'
    app_id_dimension: 'ga:dimensionX'
    start_date: 'yesterday'
    end_date: 'yesterday'
  bq:
    project_id: 'XXXXX'
    dataset_id: 'XXXXX'
    client_id_dimension: 'X'
    app_id_dimension: 'X'
google_bigquery:
  project_id: 'XXXXX'
  dataset_id: 'XXXXX'
  table_id: 'XXXXX'
